name: promptcraft
description: "Craft custom OpenRouter API requests effortlessly with this intuitive Flutter package, featuring a dynamic model selector and a sleek interface for configuring messages, parameters, and provider preferences."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
